# Generated by Django 4.0 on 2022-01-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_seller_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='company',
        ),
    ]
