# Generated by Django 4.0 on 2022-01-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_seller_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('addressLine1', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('addressLine2', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('addressLine3', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('pin', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default=True, max_length=50, null=True)),
            ],
        ),
    ]
