# Generated by Django 4.0 on 2022-01-31 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
                ('final', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('q', models.TextField(default='')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
                ('product', models.ManyToManyField(default=1, to='mainApp.Product')),
            ],
        ),
    ]
