# Generated by Django 4.0 on 2022-01-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='mode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
